4 feature step 1 consultation withh new user
korzhuk-xeniya/animal_shelter_2 pull request #18
Opened 2024-02-02 20:46 UTC by korzhuk-xeniya

2024-02-03 10:52 UTC, OlgaLugacheva requested changes

2024-02-03 10:52 UTC, OlgaLugacheva commented on telegram-bot/src/main/java/pro/sky/telegrambot/model/Animal.java
> +    @Column
column аннотация нужна, если у вас отличается имя таблицы от того, как в сущности

2024-02-03 10:52 UTC, OlgaLugacheva commented on telegram-bot/src/main/java/pro/sky/telegrambot/model/Animal.java
> +    @Column
лучше лишние убрать

2024-02-03 10:52 UTC, OlgaLugacheva commented on telegram-bot/src/main/java/pro/sky/telegrambot/model/ReportAboutAnimal.java
>      //ID репорта
может быть для простоты пока сделать фото как массив байтов, но не настаиваю

2024-02-03 10:52 UTC, OlgaLugacheva commented on telegram-bot/src/main/java/pro/sky/telegrambot/model/User.java
> +////    @OneToOne
решить, что с этим делать, вообще подумайте, может быть и не нужна вам таблица Animal , а достаточно просто имя питомца указать - но это на размышление

2024-02-03 10:52 UTC, OlgaLugacheva commented on telegram-bot/src/main/java/pro/sky/telegrambot/repository/UserRepository.java
> +//    @Query("SELECT CASE WHEN COUNT(u) > 0 THEN true ELSE false END FROM User u WHERE u.chatId = :chatId")
навести тут порядок - удалить ненужные, оставить нужны, если в разработке - пометить как todo

2024-02-03 10:52 UTC, OlgaLugacheva commented on telegram-bot/src/main/java/pro/sky/telegrambot/service/AnimalServiceImpl.java
> +//    private final Animal animal;
ну это поле тут явно не нужно, если не нужна будет таблица, то и сервис этот будет не нужен - на подумать

2024-02-03 10:52 UTC, OlgaLugacheva commented on telegram-bot/src/main/java/pro/sky/telegrambot/service/ShelterServiceImpl.java
> +            Long userId = update.message().from().id();
имейте в виду, что в дальнейшем нужно будет сохранять фото, и надо будет тут ветвиться по условиям больше

2024-02-13 19:14 UTC, korzhuk-xeniya commented on telegram-bot/src/main/java/pro/sky/telegrambot/model/Animal.java
> +    @Column
Добавили названия, поэтому аннотацию решили оставить, чтобы не было конфликта СамелКейса с sql

2024-02-13 19:15 UTC, korzhuk-xeniya commented on telegram-bot/src/main/java/pro/sky/telegrambot/model/ReportAboutAnimal.java
>      //ID репорта
Пока оставили ссылку

2024-02-13 19:16 UTC, korzhuk-xeniya commented on telegram-bot/src/main/java/pro/sky/telegrambot/model/User.java
> +////    @OneToOne
Таблицу Animal решили оставить

2024-02-13 19:17 UTC, korzhuk-xeniya commented on telegram-bot/src/main/java/pro/sky/telegrambot/repository/UserRepository.java
> +//    @Query("SELECT CASE WHEN COUNT(u) > 0 THEN true ELSE false END FROM User u WHERE u.chatId = :chatId")
часть методов уже задействовали

2024-02-13 19:17 UTC, korzhuk-xeniya commented on telegram-bot/src/main/java/pro/sky/telegrambot/service/ShelterServiceImpl.java
> +            Long userId = update.message().from().id();
хорошо, спасибо!

2024-02-17 16:11 UTC, merged